### PR TITLE
- little bug fixes and some code refactoring

### PR DESCRIPTION
**Pull request by nfz**
- added a grbl post processor - grbl does not support tool change commands and a few other things
- starting moving some of the strategies into their own functions - easier to understand getPath3axis when its not so huge.  More work to come on this.
- Skin setting gets used in all strategies but user did not have access to it in the ui for all strategies.
- sortChunks() would sometimes go into an infinite loop trying to sort the last few chunks.  Have a work around fix but this needs to be looked at for a proper fix.

### CODE REVIEW

**Comment by vilemnovak** [comment]
Hi! just saw this, quite a big amount of changes, It will take a bit of time for me to read through, so far looks great!

**Comment by vilemnovak** [comment]
ok did read through all of this, and so far the only problem I see are these:
 - git ignore - it is made so that git ignores all files, and you add files manually. Simply because I have blender CAM in blender dir with all other .py addons.
sortChunks - this I have to go through, the algorithm is quite complicated. Especially since this occured with the new changes? please, provide me with a case file.

**Comment by vilemnovak** [comment]
Please, if you can, just separate the problematic part - with sortChunks, and then we can commit the rest.
Great work otherwise! I see you understand the code well.

**Comment by nfz** [comment]
The problem with sort chunks has been there since I started using Blendercam back in August.  The problem does not occur all the time.  I haven't narrowed down the condition that triggers it yet. I had this fix in my fork in a branch for a while now since I use Blendercam for production.  I still have it in my "Seperate Operations" branch.

  I can pull it from my Master branch for now since I use the other branch for developement.

I will see if I can figure out what the condition is that triggers the problem.  I have a few .blend files that trigger the problem but have yet to figure it out.  The .blend files come from posts in the blendercam forum from many months ago that some people posted saying they had problems with them.

**Comment by nfz** [comment]
I will just comment out the code fore now and others can uncomment it if they want to experiment with it.

**Comment by nfz** [comment]
I don't put the addon in blender's directory.  I just setup the path once in Blender addon settings and then never have to worry about copying changes each time I update to a new blender daily build or make changes to Blendercam developement source.  I'll put a section in the Wiki about how to do this.

**Comment by nfz** [comment]
Didn't think I would be able to resolve the conflicts for at least a week but took another look and it wasn't that bad.

**Comment by vilemnovak** [comment]
sorry reverting, somehow I created some conflicts, don't know why, will try again soon.

**Comment by nfz** [comment]
Sorry for the delay in getting the blend file uploaded.  I have been running tests to try and get sortChunks to misbehave ie infinite loop, but it seems to be working fine now.

Here is a link to the file in the forum: https://groups.google.com/group/blender-cam-forum/attach/358afbab653d8/logo.blend?part=0.2&authuser=0

The forum post:
https://groups.google.com/forum/embed/?place=forum%2Fblender-cam-forum&theme=softgray&hideforumtitle=true&showsearch=false&showpopout=true&showtabs=true&parenturl=http%3A%2F%2Fblendercam.blogspot.fi%2Fp%2Fblog-page.html#!category-topic/blender-cam-forum/support/gHW1muVNQUY

**Pull request merged**
