### PR TITLE
Add "Enable manual tool change" checkbox to CAM Machine section

### PR DESCRIPTION
**Pull request by taras-ko**
Pull request for #43 related issue.

Using the manual tool changer only makes sense if you have tool holders
that remain with the tool (Cat, NMTB, Kwik Switch etc.)
when changed thus preserving the location of the tool to the spindle.

If you don't have such tool holders you don't need that feature.

### CODE REVIEW

**Comment by nfz** [comment]
Looks good.  The only caveat is it only effects linuxcnc and none of the other postprocessors.  I would go ahead with a merge with master and then someone can add the support for the other postprocessors later (only a few support it). But its Vilem's call.

I will test it out.

**Comment by nfz** [comment]
I think "Enable Tool Change" would be better since the code works for both manual and automatic tool change.

**Comment by nfz** [comment]
Ok, after playing with this I am a little confused as to what you are trying to do.  This patch only disables the tool change at the end of the program if manual tool change is enabled.  But it still allows tool change commands in the program.

**Comment by nfz** [comment]
Oops, my bad.  There was a conflict in the merge which caused a problem on my end.  Got it fixed now.  Seems to work properly now.

**Comment by nfz** [comment]
I am wondering if it would be better to have "Enable Tool Change" in the UI defaulting to false.  This way  users can enable it if there machines support Tx and Mx commands.  One of my machines has support for those commands but does not have an automatic tool changer.  The machine moves to the tool change position and then displays a message to change the tool to the request one.  I then select resume after changing the tool.

**Comment by nfz** [comment]
Disregard my comment about only affecting linuxcnc.  That was the result of the changes to utils.py not taking affect during the merge.

**Comment by taras-ko** [comment]
Good point. Default to false and "Enable tool change" name. Also need to change visibility of this checkbox if posprocessor supports this feature.

Пользователь Jeff Doyle <notifications@github.com> писал:

**Comment by taras-ko** [comment]
I agree with you that the tool change should be disabled by default. But.

There is one problem when I'm trying to export a chain which consist of >1 CAM operations, where each operation has it's own tool. When machine begins the next chain token operation with a different tool, at least next three thing should happened:
1. Program should be paused.
2. User should be notified "Please change tool, and press Enter to continue"

For linux EMC, notification window is appearing when there is a code line:
T<tool_number> M6

I think this line should be in the generated code by default. If I have the (semi-)automatic tool changer, or such special collets with tools I can enable an extra features, they are already implemented in tool_change() function in iso.py

At least there is one flag "output_g43_on_tool_change_line" which should be disabled by default and enabled by user. I propose just add "Use G43 on tool change" checkbox which will set this flag to true.

**Comment by nfz** [comment]
I have also been exploring options for this and decided to provide UI options for the settings in iso.py and all post-processors that sub class from it.  I will setup a branch with what I have done so far so you can have a look and test it out.

**Comment by nfz** [comment]
This is what I am using for post processing options in the UI:
postprocessoptions

A g-code header and trailer can be defined for each operation.  The machine settings allow enabling some post processor options ie tool change options.  I put in the g43 option which is only available if tool change is enabled.

**Comment by taras-ko** [comment]
Ok. Thanks. I'll test it, as soon as it will appear.

**Comment by nfz** [comment]
Its in my branch: https://github.com/nfz/blendercam/tree/ISOsettings

**Comment by nfz** [comment]
Ok, its now in the edge branch.

https://github.com/vilemnovak/blendercam/tree/edge

**Comment by nfz** [comment]
Decided not to have an edge branch.  The new features are now in the master branch but to use them you must enable the "show experimental features" in the Blender CAM addon properties.

**Comment by vilemnovak** [comment]
thanks, it will leave my head clearer when trying to put things together ;) and great to see new features coming!

**Pull request closed without merging**
