### PR TITLE
Some small fixes

### PR DESCRIPTION
**Pull request by nfz**
Just started using Blender Cam for my business.  Great work, I was able to get it up and running with my system within a few minutes and its very easy to use.

I am using Blender daily build based on 2.75 with Python 3.4.  I did notice a few small bugs having to do with machine presets.  I was trying to setup a preset for my scratch built cnc and ran in to a few little problems.

Hopefully the comments and diffs give enough info for the changes I implemented.

### CODE REVIEW

**Comment by vilemnovak** [comment]
Hi Jeff,
 thanks a lot for your work!
I will check as soon as possible on the patch and will try to merge it - I
hope to have time for this this week,
I will let you know after that how that went.
Regards
Vilem

**Comment by nfz** [comment]
Hi Vilem,

No rush.

**Comment by nfz** [comment]
Oops, sorry, forgot that when I push a commit it would automatically be added to the open pull request.  So disregard the Temp Fix commit in ops.py

**Comment by vilemnovak** [comment]
Thanks, I just found that time needed to check your work, and merged it. 
Regarding feedrate not having a unit, I went the way of not displaying any unit, since blender doesn't have speed units, but if you consider this a bit more logical, I can agree. 
Thanks, and welcome ;)

**Pull request merged**
