### PR TITLE
Added support for custom postprocessors.

### PR DESCRIPTION
**Pull request by dastultz**
Hi Vilem,

I've added support for custom post processors. The Github diff shows a lot more apparent changes, like whitespace or something. There aren't that many.

I'm not crazy about the use of the presets directory to store the custom postprocessors. I don't have any better ideas. I'm happy to talk about any changes I should make before it's accepted.

### CODE REVIEW

**Comment by nfz** [comment]
I agree that the presets directory is not the best place for postprocessors.  I will test the code and see if any ideas pop up.

**Comment by vilemnovak** [comment]
Hi, this looks interesting!
Regarding "custom" postprocessors - all postprocessors are actually custom, so we could have BlenderCAM simply read all postprocessors in the nc library somehow?
Just an opinion. otherwise, presets directory is actually not that bad. 
regarding EOL - end of line settings - the diff is very hard to read this way... I use Notepad++, it seems to be set up to EOL - windows style, and with UTF-8 encoding...

**Comment by dastultz** [comment]
On Sun, Dec 13, 2015 at 10:21 AM, vilemnovak <notifications@github.com>
wrote:

> Hi, this looks interesting!
> Regarding "custom" postprocessors - all postprocessors are actually
> custom, so we could have BlenderCAM simply read all postprocessors in the
> nc library somehow?
>
I agree, I didn't want to go too far refactoring the current code. I do
think they should all be loaded in the same manner and I wouldn't have a
problem dropping my post processor in to some BlenderCAM directory. I'll
look at it again with that in mind.

> regarding EOL - end of line settings - the diff is very hard to read this
> way... I use Notepad++, it seems to be set up to EOL - windows style, and
> with UTF-8 encoding...
>
Sorry about that. I use PyCharm on a Mac. When I went to push I got a
warning about the EOL and I thought it was offering to fix it, then I
looked at the diff on Github and saw the problem. I don't have much
experience with Git/Github, I use Mercurial at my day job.

I'll see if I can fix it.

/Daryl

**Comment by dastultz** [comment]
I followed this page here: https://help.github.com/articles/dealing-with-line-endings/
I added `.gitattributes` and set Python files to CRLF. I followed the instructions to "normalize" line endings, committed and pushed. Not sure if that invalidates this pull request.

It would seem that the `.gitattributes` if done right would take care of this problem. Can you look at the HEAD of my fork and see if I've made a bigger problem? I can toss it all and try to redo it if you can add a `.gitattributes` file that will set things up for everyone.

**Comment by nfz** [comment]
Yep, it made a bigger problem :).
Fortunately I copied the changes before your latest change.  Actually its easy to pull the important stuff from your fork.

The only issue I found was with the use of load_module() in getCustomPostProcessors().  If there is only one postprocessor to load then its not too bad.  But if all post processors are handled the same way then everyone gets loaded which is not what is wanted.  Only the user selected one should get loaded.  getCustomPostProcessors() actually gets called twice, once to fill the available post processors and then again later on during the g-code export.  On my netbook this causes quite a slow down since it only runs at 600 MHz and only has 512 megs of ram.  Not to say that my poor hardware performance should dictate what code gets used, but maybe there is a more efficient way of implementing this.

Anyway I think its a good start and agree that all post processor are custom and could be handled this way instead of hard coded.

**Comment by dastultz** [comment]
On Sun, Dec 13, 2015 at 9:15 PM, Jeff Doyle <notifications@github.com>
wrote:

> Yep, it made a bigger problem :).
>
Ok, I need some help with this then, the .gitattributes file must not be
right and I'm not sure what's desired on the project. I did find some files
that were LF rather than CRLF.

The only issue I found was with the use of load_module() in
> getCustomPostProcessors(). If there is only one postprocessor to load then
> its not too bad. But if all post processors are handled the same way then
> everyone gets loaded which is not what is wanted. Only the user selected
> one should get loaded. getCustomPostProcessors() actually gets called
> twice, once to fill the available post processors
>
But we need to populate the list with all of the post processors so you can
choose the one you want.


> and then again later on during the g-code export.
>
Yes, here we need only load the selected one. I suppose I was thinking no
one but me would have a custom post processor and even then I'd have only
one. Try to find a standard post processor, if no match, load all the
custom which would be only one. If we're going to externalize all post
processors, then that may need to change.


> On my netbook this causes quite a slow down since it only runs at 600 MHz
> and only has 512 megs of ram. Not to say that my poor hardware performance
> should dictate what code gets used, but maybe there is a more efficient way
> of implementing this.
>
I'm a bit surprised by this. Are you saying load_module() is slow? My
thought was that I was first simply loading a "definition" of the custom
post processor, then at g-code export time instantiating the actual
Creator. That seemed a reasonable approach to me.

Well, I think I need some more direction from the team if I'm to do more
here. Also need help with the line ending thing. Maybe I'll trash my fork
and try again. I exported a patch before I created the fork...

/Daryl

**Comment by vilemnovak** [comment]
guys, so, I could solve this way - I can now switch ALL endings inside Blender CAM to UNIX. than, you'd have to manually apply, but we can then have clear decision on how this is handled. What do you think? If you agree, I'll do this asap.

**Comment by dastultz** [comment]
On Mon, Dec 14, 2015 at 10:09 AM, vilemnovak <notifications@github.com>
wrote:

> guys, so, I could solve this way - I can now switch ALL endings inside
> Blender CAM to UNIX. than, you'd have to manually apply, but we can then
> have clear decision on how this is handled. What do you think? If you
> agree, I'll do this asap.
>
It does appear to me that LF is the common EOL, though maybe I read the
Github docs wrong. I don't have a problem reapplying, I've got just the one
small feature in progress. So I approve.

/Daryl

**Comment by nfz** [comment]
This may help:
https://help.github.com/articles/dealing-with-line-endings/#platform-windows

**Comment by dastultz** [comment]
I'd like to finish the feature up and then get some minor bug fixes done. Are we going to move to Unix line endings?

**Comment by vilemnovak** [comment]
Hi, I didn't yet move to new endings, sorry, not sure if to proceed, is it ok for everybody?

**Comment by nfz** [comment]
Try it.  It is usually just a git setting.

**Comment by dastultz** [comment]
On Fri, Dec 25, 2015 at 2:15 PM, Jeff Doyle <notifications@github.com>
wrote:

> Try it. It is usually just a git setting.
>

I have suggested we have a .gitattributes file in the repo which will
ensure that we all have the same setting/behavior. Vilem, I suggest you add
.gitattributes to the project configured for unix line endings. Then the
rest of us shouldn't have to do anything special. That's my understanding
anyway.

It sounds like Jeff is OK with the switch, I am.

/Daryl

**Comment by vilemnovak** [comment]
Hi, this is probably too old now, and would have to be done as a whole new things, so will close for now. Feel free to reopen anytime.

**Pull request closed without merging**
